[tool.black]
line-length=120

[tool.isort]
profile = "black"
force_single_line = true
known_third_party = ["viktor"]

[tool.pylint.master]
max-line-length = 120

[tool.pylint.imports]
known-third-party="viktor"

[tool.pylint.messages_control]
disable = [
    "import-error", "unused-argument", "too-few-public-methods", "no-self-use"
]
